### ISSUE TITLE
check_until_complete fails when workflow is manually killed

### ISSUE THREAD

**Issue by TheFirstAvenger** [OpenAperture/oa_deployer#1]
```elixir
** (Poison.SyntaxError) Unexpected token: O
    lib/poison/parser.ex:56: Poison.Parser.parse!/2
    lib/poison.ex:83: Poison.decode!/2
    (oa_deployer) lib/oa_deployer.ex:94: OaDeployer.check_until_complete/7
    (oa_deployer) lib/oa_deployer.ex:7: OaDeployer.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by TheFirstAvenger** [comment]
Same with handling an error in the workflow (install.sh didn't have +x permission):

```elixir
Created workflow 0ed74e41-e238-4d0a-b216-bd838f825879
Workflow 0ed74e41-e238-4d0a-b216-bd838f825879 execution started
Started milestone build
Milestone build in progress...
Milestone build in progress...
Milestone build in progress...
** (Poison.SyntaxError) Unexpected token: O
    lib/poison/parser.ex:56: Poison.Parser.parse!/2
    lib/poison.ex:83: Poison.decode!/2
    (oa_deployer) lib/oa_deployer.ex:94: OaDeployer.check_until_complete/7
    (oa_deployer) lib/oa_deployer.ex:7: OaDeployer.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```
